---
- name: Register Keys for Debian Buster
  apt_key:
    url: "{{ item }}"
    state: present
  become: yes
  ignore_errors: yes
  with_items:
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://baltocdn.com/helm/signing.asc
    - https://download.docker.com/linux/debian/gpg
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"

- name: Add kubernetes repository for Debian Buster
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes
  with_items:
    - deb https://apt.kubernetes.io/ kubernetes-xenial main
    - deb https://baltocdn.com/helm/stable/debian/ all main
    - deb https://download.docker.com/linux/debian buster stable
  when: 
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"

- name: Install kubernetes Packages
  apt:
    name: [ 'kubeadm', 'kubelet', 'kubectl', 'containerd', 'helm' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes
